- index.js
This is related to https://github.com/ember-cli/ember-cli/pull/2965.  Addons that come along for the ride OTB, should do their upmost to be completely configurable. :smile:
> Removed hardcorded destDir

- blueprints/ember-cli-qunit/index.js
> update to 1.16

- blueprints/ember-cli-qunit/index.js
This was already updated upstream, just want to make sure we keep these
in sync.
> Update blueprint installed package versions.

- blueprints/ember-cli-qunit/index.js
- index.js
- templates/test-body.html
- vendor/ember-cli-qunit/qunit-configuration.js
- vendor/ember-cli-qunit/test-loader.js
* Update URL for ember-cli-shims.
* Add ember-cli-test-loader to `bower.json` in blueprint.
* Add QUnit config for notifications.
* Add QUnit config for disabling JSHint.
* Add ember-testing-container elements via `contentFor('test-body')` hook.
* Add ability hiding container via QUnit config (formerly in ember-cli-test-loader).
> Move test-loader into ember-cli-qunit.

- blueprints/ember-cli-qunit/index.js
> Bump ember-qunit to v0.2.1

- blueprints/ember-cli-qunit/index.js
ember-cli/ember-cli@51e593341986ab34d9dfecf5c88b780121e44b0d
```bash
$ ember new some-project
$ ember generate ember-cli-qunit
$ git diff
```
```diff
diff --git a/bower.json b/bower.json
index bc6dd6b..94eab9c 100644
--- a/bower.json
+++ b/bower.json
@@ -12,6 +12,6 @@
"ember-load-initializers": "ember-cli/ember-load-initializers#0.0.2",
"ember-qunit": "0.2.6",
"ember-qunit-notifications": "0.0.5",
-    "qunit": "~1.17.1"
+    "qunit": "~1.17.0"
}
}
```
> Match the ember-cli blueprint

- blueprints/ember-cli-qunit/index.js
> Update ember-qunit dependencies

- index.js
- package.json
Before:
```
% ember build --silent
app.js: line 6, col 1, Expected an assignment or function call and instead saw an expression.
app.js: line 6, col 6, Missing semicolon.
2 errors
===== 1 JSHint Error
```
After:
```
% ember build --silent
%
```
> Use `ui` if present for linting and logging.

- vendor/ember-cli-qunit/qunit-configuration.js
- vendor/ember-cli-qunit/test-container-styles.css
Based on suggestions from #38, allow the location of the preview window to be toggleable.
> Feature: Allow testing preview container position to be toggleable

- vendor/ember-cli-qunit/test-loader.js
Applying the changes of ember-cli/ember-cli-test-loader#10 here
> Exclude the project name when requiring files

- vendor/ember-cli-qunit/qunit-configuration.js
Well, that is embarrassing.
I totally forgot to put a semi-colon on this last time.
> Adding in a semi-colon

- blueprints/ember-cli-qunit/index.js
> Update ember-qunit to v0.3.2

- package.json
Bug Fixed: 
https://github.com/rwjblue/broccoli-jshint/commit/e088cf910dac1e3f8404f13ac881de1c9eddff99
> Updated broccoli-jshint to 0.5.6.

- blueprints/ember-cli-qunit/index.js
> Bump ember-qunit version to 0.4.0

- vendor/ember-cli-qunit/test-loader.js
Dovetails with https://github.com/ember-cli/ember-cli-test-loader/pull/14.
> Use addModuleIncludeMatcher instead of prototype mutation.

- index.js
This PR implements the abstract `Project.generateTestFile()` method introduced by ember-cli/ember-cli#5508
> Implement test file generator function

- index.js
- package.json
Use `broccoli-concat` instead of `broccoli-soucremap-concat` which has been merged back into `broccoli-concat`
> Use broccoli-concat instead of broccoli-soucremap-concat

- blueprints/ember-cli-qunit/index.js
- index.js
- package.json
Preparing for for ember-cli-qunit@2.0.0.
> Remove backwards compat shims.

- index.js
Too many double negatives making https://github.com/ember-cli/ember-cli-qunit/issues/150 hard to reason about.
> Fix boolean for acceptance testing container styles.

- index.js
- package.json
... and remove "klassy" (see emberjs/ember-test-helpers#183 and https://github.com/emberjs/ember-qunit/pull/249)
/cc @rwjblue @trentmwillis
> Update "ember-qunit" to v2.0.0-beta.1

- index.js
For when https://github.com/ember-cli/ember-cli/pull/6555 lands.
> Preprocess addon-test-support files in upcoming ember-cli

- index.js
Backport of https://github.com/ember-cli/ember-cli-qunit/pull/159.
> [2.x] Preprocess addon-test-support files in upcoming ember-cli

- package.json
- yarn.lock
Fixes https://github.com/ember-cli/ember-cli-qunit/issues/185
> Bump ember-cli-babel for Node 8 support

- index.js
This was not needed :(
See https://github.com/ember-cli/ember-cli/issues/7374 and https://github.com/emberjs/ember-qunit/pull/284.
> Remove `setTestGenerator` shenanigans.

- package.json
- testem.js
- yarn.lock
* Update to ember-cli-babel@6.11
* Update to ember-qunit@3.3.1
> Update dependencies to latest versions.
