- .gitignore
- index.js
- vendor/ember-cli-qunit/test-container-styles.css
Once this lands, we can remove https://github.com/ember-cli/ember-cli/blob/e78168ba4a293a28474fab795f1c93fc4dde0988/blueprints/app/files/tests/index.html#L16-L31 as the inline styles cause issues with CSP.
> Allow ember-cli to remove inline styles.

- index.js
Because postprocessTree runs in series and we need to run linters in parallel.
> Switch to a dedicated lintTree hook

- blueprints/ember-cli-qunit/index.js
- index.js
Updates to allow either ember-qunit 0.1.x or ember-qunit 0.2.x (by checking for the existence of the specific file locations).
Needs to wait until ember-qunit 0.2.0 is shipped (which is blocked on https://github.com/switchfly/ember-test-helpers/pull/12 at the moment).
> Update to ember-qunit 0.2.0.

- vendor/ember-cli-qunit/qunit-configuration.js
- vendor/ember-cli-qunit/test-loader.js
This deals with a Chrome bug where if a breakpoint is hit during the evaluation of the page the sourcemaps will not continue to load.
> Add a short delay before starting tests.

- blueprints/ember-cli-qunit/index.js
I finally got the bower registry updated so that `ember-qunit` points to the builds registry now.
> Fix target for ember-qunit.

- blueprints/ember-cli-qunit/index.js
- index.js
The `qunit` shim is now provided by `ember-qunit` itself (instead of ember-cli-shims).
> Remove ember-cli-shims requirement.

- blueprints/ember-cli-qunit/index.js
Changes from https://github.com/ember-cli/ember-cli-test-loader/pull/7.
> Prevents module load errors from stopping test run.

- blueprints/ember-cli-qunit/index.js
- vendor/ember-cli-qunit/test-loader.js
Previously, if a given test failed to load we would `console.error` the failure, which may or may not help folks find them.  
This PR makes those module load failures actual fail a test, so that you get decent warning/info that a whole module of your tests cannot be run.
> Ensure modules that fail to load fail the build.

- index.js
This change allows you to remove `"ember-qunit-notifications"` from your project's bower.json if you don't care much for the notifications and rather just have 1 less dependency.
> Remove ember-qunit-notifications dependency

- blueprints/ember-cli-qunit/index.js
Fixes #54 
`ember-qunit@0.3.0` contains fix for https://github.com/emberjs/data/issues/2924, which resolves issue of container being shared across tests via `this.subject()`
> Upgrade ember-qunit to 0.3.0

- vendor/ember-cli-qunit/qunit-configuration.js
- vendor/ember-cli-qunit/test-loader.js
Read `QUnit.config.autostart` after `test-helper` and friends have had a chance
to set the value.  Load the tests in either case, but only start them
automatically if `QUnit.config.autostart` has not been set to false.
This is particularly useful for users who want to debug tests in PhantomJS.
> Respect user autostart settings.

- vendor/ember-cli-qunit/qunit-configuration.js
So, we had a developer check in a test that hung our build all weekend.
I would like to propose putting in a default test timeout into this package.
I think that 5 minutes is a really long time for qunit tests, but I'm not sure what kind of long running tests people might have.
I'm open to suggestions regarding the duration of the default timeout.
> Adding a default timeout for QUnit tests.

- vendor/ember-cli-qunit/qunit-configuration.js
This PR so far only changes the string displayed in the UI. The rest of the code still refers to this option as `doccontainer`. Should all these instances also be changed to `dockcontainer`?
As an aside, it seems to be called a container in one option ("Hide container") but as a test pane in another ("Doc test pane"). Should these be made consistent?
> Correct "Doc test pane" to "Dock test pane"

- blueprints/ember-cli-qunit/index.js
> Fix default blueprint by specifying source.

- package.json
Latest broccoli-jshint uses latest version of broccoli-filter, which as performance improvements.
> Upgrading broccoli-jshint to the latest

- vendor/ember-cli-qunit/qunit-configuration.js
QUnit runs tests just fine without any modifications to the DOM. This change is important for running tests that require the application being set on the `<body>` element (scrolling-related in particular) or have CSS that is impacted by the modified application structure.
> Allow #ember-testing-container to be optional.

- index.js
Closes ember-cli/ember-cli#4586 by providing additional options:
```javascript
{
insertContentForTestBody: false,
useLintTree: false
}
```
Potentially blocked by ember-cli/ember-cli#4923
Also makes `disableContainerStyles` require being explicitly set to `false`. Being `undefined` means that we should use the default behavior since no settings were changed. This will allow us to remove [unnecessary coupling between ember-cli and ember-cli-qunit here](https://github.com/ember-cli/ember-cli/blob/97d048f89db3aea9852985b3904f4144093ef92f/lib/broccoli/ember-app.js#L172-L174).
> Add additional configuration options.

- index.js
Addresses #83
Tested on ember-cli 0.2.7 & 1.13.8 & master
> Fixes the useLintTree: false scenario

- blueprints/ember-cli-qunit/index.js
- index.js
- package.json
This removes ember-qunit as a bower dependency (in favor of using NPM
directly).
Currently, this adds ember-qunit, ember-test-helpers, and klassy
(required by ember-test-helpers) to `vendor.js`. That is slightly
unfortunate, as ideally these would be added to `test-support.js`
instead, however there is no mechanism other than `app.import` in
ember-cli today (1.13.x timeframe) to handle this.
IMO, we should add a `addon-test-support` tree, that appends to
`test-support.js` by default. This would allow addons to provide test
helpers much simpler than we can today.
> Use ember-qunit as an NPM dependency.

- index.js
Hey there,
as discussed with @rwjblue at https://github.com/switchfly/ember-cli-mocha/pull/95, use `this._super.included.call(this, target)` instead of `this._super.included(target)` in `included` function.
> Use `this._super.included.call(this, target)` in `included` function.

- index.js
ember-cli@2.2.0-beta.{1,2} had a bug that caused all legacy test files to be appended in the wrong order. This meant when 1.2.0 was released of ember-cli-qunit things completely broke (because QUnit was expected before it was included in the file). The underlying issue was fixed upstream and released in ember-cli@2.2.0-beta.3 (in https://github.com/ember-cli/ember-cli/pull/5274).
This PR adds support for pulling qunit from `bower.json` on ember-cli's < 2.2.0-beta.3 and uses NPM on ember-cli's >= 2.2.0-beta.3.
> Fix issues with 1.2.0+ and ember-cli@2.2.0-beta.{1,2}.

- index.js
This will allow ember-cli-eslint to take priority when present (and not require users to disable ember-cli-qunit's linting manually).
> Disabling JSHint linting when linting addon exists.

- .travis.yml
- config/ember-try.js
- package.json
- vendor/ember-cli-qunit/test-loader.js
Addressing #110 and #109.
Also, fixed up some stuff so that tests can run after cloning and `npm install && bower install`. It also enables Travis to be turned on.
> Do not require upgrading test-loader

- README.md
- index.js
- package.json
This PR removes the JSHint-based lintTree that has been extracted into the [ember-cli-jshint](https://www.npmjs.com/package/ember-cli-jshint) addon.
This can most-likely be considered a breaking change and should result in a major version bump.
see also https://github.com/ember-cli/ember-cli/pull/5757
> Remove JSHint lintTree

- .travis.yml
- blueprints/ember-cli-qunit/index.js
- bower.json
- config/ember-try.js
- package.json
- tests/unit/test-loader-test.js
- vendor/ember-cli-qunit/test-loader.js
In preparation of `ember-cli-test-loader@1.0.0`. Since the lookup path for `TestLoader` changes, this seems difficult to make backwards compatible. Only idea I have would be to wrap the `require` in a `try...catch` and attempt one path and then the other.
Note: this won't work until ember-cli/ember-cli#5709 lands.
> Prepare for test-loader being in NPM

- vendor/ember-cli-qunit/test-loader.js
Addressing issue #100 with the second approach mentioned in that issue.
Loading failures show up with a filter now:
Existing behavior is retained with an added global failure of all the test modules that didn't load:
> Re-throw TestLoader failures during QUnit.done

- index.js
Addressing #122. ~~Added some simple caching as well, not sure if it's beneficial or not.~~ These changes seem to cut startup times by about 50% on average.
cc @stefanpenner
> Make requires lazy to improve startup times

- vendor/ember-cli-qunit/qunit-configuration.js
- vendor/ember-cli-qunit/test-container-styles.css
**Description**
Adds a new config option to enable a "development" mode that includes a full-screen takeover for the container and removes the test timeout limit.
**Motivation**
When building out features that rely on dynamic or not-yet-ready APIs, it is desirable to be able to work directly with static/mock data. In order to encourage TDD (and testing in general), it would be nice to enable a "development mode" so that developers can more easily interact with the application during an Acceptance test that leverages mock data.
This primarily involves two things:
1. Increasing the size of the container such that it looks and feels like the application normally does.
2. Removing test timeouts so that if a developer uses `pauseTest()` it won't err out on them.
A secondary benefit here is …
> Introduce development mode option

- README.md
…since there's no changelog to explain the major version bump
> Add a README note about JSHint extraction in 2.x

- vendor/ember-cli-qunit/qunit-configuration.js
- vendor/ember-cli-qunit/test-loader.js
In #136 we added support for running without jQuery by using standard
DOM API's for DOM loaded instead of using jQuery for it. Unfortunately,
that change broke the ability to use IE8 (without a major version bump)
because IE8 doesn't support the DOMContentLoaded event properly.
This change brings back usage of `jQuery` when present, but falls back
to using `DOMContentLoaded` when `jQuery` is not available.
> Use jQuery if it is present.

- package.json
- tests/acceptance/adapter-test.js
- tests/dummy/app/router.js
- tests/dummy/app/templates/application.hbs
- tests/dummy/app/templates/other-page.hbs
- vendor/ember-cli-qunit/test-loader.js
Corollary to https://github.com/rwjblue/ember-qunit/pull/234.
Only real change here is to provide a new test adapter for handling async. This might belong in `ember-qunit` as opposed to this addon, but adding it here was way easier.
> Upgrade QUnit to 2.0

- vendor/ember-cli-qunit/test-container-styles.css
Prior to this change, the testing preview would have the proper width but only half the height.
> Use 2x for height and width of #ember-testing.

- vendor/ember-cli-qunit/test-loader.js
Under jQuery 3.0 `$.ready` is always async (even if the document is already loaded). This is generally a great thing, however we were relying on the fact that it was sync (then adding our own async to ensure it was async).
This change prevents QUnit from auto-starting until our callback is completed.
Related to https://github.com/ember-cli/ember-cli/issues/6247.
> Prevent calling `QUnit.start` twice with jQuery 3.0.

- config/ember-try.js
- index.js
Replacing the bad version check with a feature check instead. Tested with a linked version of Ember-CLI and all seems good this time.
cc/ @rwjblue
> Replace version check with babel options check

- vendor/ember-cli-qunit/test-container-styles.css
When running the tests in **development mode** the height is not overridden causing the container to have twice the height.
> Override height in full-screen mode

- .travis.yml
- index.js
Setting `this.options` inside of `included` to the options from `lib/broccoli/ember-app` means that we will attempt to transpile with the `options.babel` that the host app / addon is using. Which, as of, 2.13+ that will be babel@6 and therefore incompatible options with ember-cli-babel@5 (which this addon uses).
> Prevent clobbering custom `this.options.babel`.

- vendor/ember-cli-qunit/test-container-styles.css
the `#ember-testing-container` has a z-index of 9999, which I'm guessing is random.  However, the Module dropdown in the Qunit header has a z-index of 99, so when passed tests are hidden and all tests pass, the `#ember-testing-container` covers the dropdown without this fix.  See https://monosnap.com/file/ouYQKdxc1mMzMpStK9SCp3iUnN6eLQ.  I changed `.full-screen` just for consistency, though it works properly either way.
> don't cover open Module drop-down

- addon-test-support/ember-cli-qunit.js
Hi, there are some little things in the test ui thats bugging me. Don't know if anyone have notices them before.
**Before:**
**After:**
> docked testContainer should stick to the bottom of the window

- RELEASE.md
I went to do a new release and realized I no longer knew how to perform a proper release. Looking at the commit log, it appears similar to [ember-qunit](https://github.com/emberjs/ember-qunit/blob/master/RELEASE.md), so I lifted those instructions for here.
@rwjblue can you verify if this is accurate?
> Add RELEASE.md documentation

- index.js
There is no default implementation for `contentFor` or `setTestGenerator` in ember-cli's addon model, which means that nested addons do not have the ability to provide these hooks unless the including addon directly implements the hook and defers to the child addon.
This implements `contentFor` and `setTestGenerator` so that we can let `ember-qunit` do all the heavy lifting...
> Ensure contentFor and setTestGenerator are forwarded to ember-qunit.

- package.json
This version brings two main changes:
* Ensures re-exports from ember-test-helpers are still present (with a
deprecation).
* Ensures that `Ember.testing` is set properly from "normal" non
`moduleFor*` and/or `setup*Test` style tests.
> Update minimum version of ember-qunit.

- package.json
- yarn.lock
The bump to `ember-qunit` fixed a bug in our app.
New installs of `ember-cli-qunit` would have gotten the bugfix, due to the caret dependency, but existing installs don't show `ember-cli-qunit` as outdated at all. I'm wondering what's the best way to handle this sort of thing at a conceptual level? (Basically, if I'm an addon, and I depend on an addon that gets a bugfix, how can I best let my consumers know?)
This was very tricky for me to find and took several hours so I'm wondering how to best help & teach this to others.
> Upgrade ember-qunit
